import "@unocss/reset/tailwind.css"
import "@/styles/global.scss"

import type { Metadata } from "next"
import NextTopLoader from "nextjs-toploader"

import Footer from "@/components/layout/footer"
import Header from "@/components/layout/header"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <NextTopLoader />
        <Header />
        <main>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
