import "@unocss/reset/tailwind.css"
import "@/styles/global.scss"

import type { Metadata, Viewport } from "next"
import NextTopLoader from "nextjs-toploader"

import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  colorScheme: "only light",
  themeColor: "#ffffff",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <NextTopLoader />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
